Models/Summernote.cs
namespace AppMvc.Net.Models;

public class Summernote
{
    public Summernote(string idEditor, bool loadLibrary = true )
    {
        IdEditor = idEditor;
        LoadLibrary = loadLibrary;
    }
    public string IdEditor { get; set; }
    public bool LoadLibrary { get; set; }

    public int Heigt { get; set; } = 120;

    public string Toolbar { get; set; } = @" [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'video', 'elfinder']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]";

}

Areas/Blog/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppMvc.Net.Models;
using Microsoft.AspNetCore.Authorization;
using App.Data;
using App.Models;
using Microsoft.AspNetCore.Identity;
using AppMvc.Net.Areas.Blog.Models;

namespace AppMvc.Net.Areas.Blog.Controllers
{
    [Area("Blog")]
    [Route("admin/blog/post/[action]/{id?}")]
    [Authorize(Roles = RoleName.Administrator+ "," + RoleName.Editor)]
    public class PostController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        [TempData]
        public string StatusMessage { get; set; }

        public PostController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Post
        public async Task<IActionResult> Index([FromQuery(Name="p")]int currentPage, int pageSize)
        {
            //var appDbContext = _context.Posts.Include(p => p.Author);
            var posts = _context.Posts.Include(p => p.Author).OrderByDescending(p => p.DateUpdated);
            int totalPosts = await posts.CountAsync();
            if (pageSize <= 0 ) pageSize = 10;
            int countPages = (int) Math.Ceiling((double)totalPosts/pageSize);
            if(currentPage > countPages) currentPage = countPages;
            if(currentPage < 1) currentPage = 1;
            var pagingModel = new PagingModel
            {
                countpages = countPages,
                currentpage = currentPage,
                generateUrl = (pageNumber) => Url.Action("Index", new {
                    p = pageNumber,
                    pageSize = pageSize
                })

            };
            ViewBag.postIndex = (currentPage - 1) * pageSize;
            ViewBag.PagingModel = pagingModel;
            ViewBag.totalPosts = totalPosts;
            var postInPage = await posts.Skip((currentPage -1) * pageSize)
                                    .Take(pageSize)
                                    .Include(p => p.PostCategories)
                                    .ThenInclude(pc => pc.Category)
                                    .ToListAsync();
            return View(postInPage);

            //  var qr = _userManager.Users.OrderBy(u => u.UserName);

            // model.totalUsers = await qr.CountAsync();
            // model.countPages = (int)Math.Ceiling((double)model.totalUsers / model.ITEMS_PER_PAGE);

            // if (model.currentPage < 1)
            //     model.currentPage = 1;
            // if (model.currentPage > model.countPages)
            //     model.currentPage = model.countPages;

            // var qr1 = qr.Skip((model.currentPage - 1) * model.ITEMS_PER_PAGE)
            //             .Take(model.ITEMS_PER_PAGE)
            //             .Select(u => new UserAndRole() {
            //                 Id = u.Id,
            //                 UserName = u.UserName,
            //             });

            // model.users = await qr1.ToListAsync();

            // foreach (var user in model.users)
            // {
            //     var roles = await _userManager.GetRolesAsync(user);
            //     user.RoleNames = string.Join(",", roles);
            // } 
            
            //return View(await posts.ToListAsync());
        }

        // GET: Post/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Author)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Post/Create
        // public IActionResult Create()
        // {
        //     ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id");
        //     return View();
        // }

        public async Task<IActionResult> CreateAsync()
        {
            var categories  =  await _context.Category.ToListAsync();
            ViewData["categories"] = new MultiSelectList(categories, "Id", "Title");
            return View();

        }

        // POST: Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,Slug,Content,Published, CategoryIds")] CreatePostModel createPostModel)
        {
           var categories  =  await _context.Category.ToListAsync();
             ViewData["categories"] = new MultiSelectList(categories, "Id", "Title");
              if(await _context.Posts.AnyAsync(p => p.Slug == createPostModel.Slug) )
             {
                 ModelState.AddModelError("Slug", "Nhập chuỗi Url khác");
                 return View(createPostModel);

             }
            //  if(createPostModel.Slug == null)
            //  {
            //     var slug = AppUtilities.GenerateSlug(createPostModel.Title);
            //     ModelState.SetModelValue("Slug", new ValueProviderResult(slug));

            //  }
           
            if (ModelState.IsValid)
            {
                  Post post = new Post 
             {
                Title = createPostModel.Title,
                Description = createPostModel.Description,
                Slug = createPostModel.Slug,
                Published = createPostModel.Published,
                Content = createPostModel.Content,


             };
            
                var user =  _userManager.GetUserAsync(this.User).Result;
                 post.DateCreated = post.DateUpdated = DateTime.Now;
                 post.AuthorId = user.Id.ToString();
                _context.Add(post);

                   if(createPostModel.CategoryIds != null)
                {
                    foreach(var CateId in createPostModel.CategoryIds)
                    {
                        var postCategory = new PostCategory
                        {
                            CategoryId = CateId,
                            Post = post
                        };
                        _context.Add(postCategory);

                    }

                }
              
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            // ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", post.AuthorId);
            return View(createPostModel);
        }

        // GET: Post/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var post = await _context.Posts.FindAsync(id);
            var post = await _context.Posts.Include(p => p.PostCategories).FirstOrDefaultAsync(p => p.PostId == id);
            if (post == null)
            {
                return NotFound();
            }
            var postEdit = new CreatePostModel
            {
                PostId = post.PostId,
                Title = post.Title,
                Content = post.Content,
                Description = post.Description,
                Slug = post.Slug,
                Published = post.Published,
                CategoryIds = post.PostCategories.Select(pc => pc.CategoryId).ToArray()
            };
            //ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", post.AuthorId);
             var categories  =  await _context.Category.ToListAsync();
             ViewData["categories"] = new MultiSelectList(categories, "Id", "Title");
            return View(postEdit);
        }

        // POST: Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Description,Slug,Content,Published, CategoryIds")] CreatePostModel post)
        {
            var categories  =  await _context.Category.ToListAsync();
             ViewData["categories"] = new MultiSelectList(categories, "Id", "Title");
            if (id != post.PostId)
            {
                return NotFound();
            }
                if(await _context.Posts.AnyAsync(p => p.Slug == post.Slug && p.PostId !=id) )
             {
                 ModelState.AddModelError("Slug", "Nhập chuỗi Url khác");
                 return View(post);

             }

            if (ModelState.IsValid)
            {
                try
                {
                      var postUpdate = await _context.Posts.Include(p => p.PostCategories).FirstOrDefaultAsync(p => p.PostId == id);
                      if(postUpdate == null)
                      {
                        return NotFound();
                      }
                      postUpdate.Title = post.Title;
                      postUpdate.Description = post.Description;
                      postUpdate.Slug = post.Slug;
                      postUpdate.Content = post.Content;
                      postUpdate.Published = post.Published;
                      var odlCateIds = postUpdate.PostCategories.Select(pc => pc.CategoryId).ToArray();
                      var newCateIds = post.CategoryIds;
                      var removeCatePosts = from postCate in postUpdate.PostCategories
                                            where(!newCateIds.Contains(postCate.CategoryId))
                                            select postCate;
                        _context.PostCategories.RemoveRange(removeCatePosts);

Controllers/PlanetController.cs
using AppMVC.Net.Services;
using Microsoft.AspNetCore.Mvc;

namespace AppMvc.Net.Controllers
{
    //[Route("he-mat-troi")] //khi đã thiết lập route cho controller thì bắt buộc phải thiết lập cho action. 
    //trong trường hợp ko thiết lập cho action thì phải thêm tham só action vào route trong controller
     [Route("he-mat-troi/[action]")]
    public class PlanetController : Controller
    {
        private readonly PlanetService _planetService;
        private readonly ILogger<PlanetController> _logger;

        public PlanetController(PlanetService planetService, ILogger<PlanetController> logger)
        {
            _planetService = planetService;
            _logger  = logger;
        }
        [BindProperty(SupportsGet =true, Name = "action")]
        public string Name { get; set; }
        // GET: Planet
        //[Route("danh-sach-cac-hanh-tinh.html")]  //he-mat-troi/danh-sach-cac-hanh-tinh.html
        [Route("/danh-sach-cac-hanh-tinh.html")] ///danh-sach-cac-hanh-tinh.html
        public ActionResult Index()
        {
            return View();
        }
        public IActionResult Mercury()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Venus()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Earth()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Mars()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        [HttpGet("/saomoc.html")]
        public IActionResult Jupiter()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Saturn()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        public IActionResult Uranus()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        [Route("sao/[action]", Order = 3, Name = "neptune3")] //sao/Neptune
        [Route("sao/[controller]/[action]", Order = 2, Name = "neptune2")] //sao/Planet/Neptune
        [Route("[controller]-[action].html", Order = 1, Name = "neptune1")]  //Planet-Neptune.html
        //Route có thể đc khai báo nhiều lần. Khi gọi thẻ a có action và controller thì chương trình tự chọn ngẫu nhiên 1 trong 3 route để phát sinh url
        //trong trường hợp muốn đặt thứ tự ưu tiên thì dùng tham số Order
        //tham số Name có thể dùng để phát sinh url trong view: @Url.RouteUrl("neptune1")
        public IActionResult Neptune()
        {
            var planet = _planetService.Where(p => p.Name == Name).FirstOrDefault();
            return View("Detail", planet);
        }
        //id là tham số thông thường của Route còn các tham số đặc biệt controller, action, area thì đặt trong dấu ngoặc vuông [controller] [action] [area]
        [Route("hanhtinh/{id:int}")] //hanhtinh/1
        public IActionResult PlanetInfo(int id)
        {
            var planet = _planetService.Where(p=>p.Id == id).FirstOrDefault();
            return View("Detail",planet);

        }

    }
}

Views/Shared/_AlertMessage.cshtml
@{
    var message = TempData["StatusMessage"] as string;
}
@if(!string.IsNullOrEmpty(message))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    @message
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

}

Views/Shared/_CartPartial.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@inject CartService _cartService;


@{
    var cart = _cartService.GetCartItems();
    if (cart.Count > 0) {
        <div class="nav-item"><a class="text-warning" asp-route="cart"><i class="fa-regular fa-cart-shopping"></i>(@cart.Count)</a></div>
         
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppMvc.Net</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppMvc.Net.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" asp-append-version="true" />
   <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>y 
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 app-navbar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppMvc.Net</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Blog" asp-controller="ViewPost"
                                asp-action="Index">Blog</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Product" asp-controller="ViewProduct"
                                asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet"
                                asp-action="Index">Planet</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Contact" asp-controller="Contact"
                                asp-action="SendContact"><i class="fas fa-phone-alt"></i>Liên hệ</a>
                        </li>
                    </ul>
                    @await Html.PartialAsync("_CartPartial") 
                    <partial name="_LoginPartial" />

                    <partial name="_MenuManagePartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted app-footer">
        <div class="container">
            &copy; 2024 - AppMvc.Net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
     @* <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>  *@
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@using App.Models
@using AppMvc.Net.Menu
@inject UserManager<AppUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>
    <!-- Custom fonts for this template-->
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/lib//jquery-easing/jquery.easing.min.js"></script>



</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home"
                asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">AppMvc.Net</div>
            </a>
            @await RenderSectionAsync("Sidebar", false)
            @* @{
                var item1 = new SidebarItem()
            {
                Type = SidebarItemType.Divider
            };
                var item2 = new SidebarItem()
            {
                Type = SidebarItemType.Heading,
                Title = "Đây là tiêu đề"
            };
                var item3 = new SidebarItem()
            {
                Type = SidebarItemType.NavItem,
                Title = "Đây là tiêu đề",
                Items = null,
                Controller = "Contact",
                Action = "Index",
                Area = "Contact",
                AweSomeIcon = "far fa-address-book",
                IsActive = true
            };
                var item4 = new SidebarItem()
            {
                Type = SidebarItemType.NavItem,
                Title = "ABC Xyz",
                AweSomeIcon = "far fa-address-book",
                IsActive = true,
                collapseId = "item4",
                Items = new List<SidebarItem>()
            {
            new SidebarItem()
            {
            Type = SidebarItemType.NavItem,
            Title = "Menu con 1",
            Items = null,
            Controller = "Contact",
            Action = "Index",
            Area = "Contact",

            },
             new SidebarItem()
            {
            Type = SidebarItemType.NavItem,
            Title = "Menu con 2",
            Items = null,
            Controller = "Contact",
            Action = "Index",
            Area = "Contact",

            }
            }
            };


            }
            @Html.Raw(item1.RenderHtml(Url))
            @Html.Raw(item2.RenderHtml(Url))
            @Html.Raw(item3.RenderHtml(Url))
                        @Html.Raw(item4.RenderHtml(Url)) *@



            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <h1>@ViewData["Title"]</h1>


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><i class="fas fa-user"></i>
                                    @UserManager.GetUserName(User)!</span>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-controller="Manage" asp-action="Index" asp-area="Identity">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Hồ sơ
                                </a>
                                <div class="dropdown-divider"></div>
                                <form class="dropdown-item" asp-area="Identity" asp-controller="Account"
                                    asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
                                    <button title="Đăng xuất" type="submit" class="btn navbar-btn navbar-link"><i
                                            class="fas fa-sign-out-alt"></i> Đăng xuất</button>
                                </form>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; AppMvc.Net 2024</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)


</body>

</html>

Views/Shared/_MenuManagePartial.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService

@{
  var result = await authorizationService.AuthorizeAsync(this.User, "ViewManageMenu");
}
@if (result.Succeeded)
{
  <a class="nav-link text-light" asp-action="Index" asp-controller="AdminCP" asp-area="AdminCP" ><i class="fas fa-cog"></i>Quản trị</a>
  //Bỏ menu này chỉ dùng menu quản trị sidebar mới thêm bên trên 
  @* <div class="dropdown ">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown"
      aria-expanded="false"><i class="fas fa-cog"></i>
      Manage
    </a>
    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
      <li> <a class="dropdown-item" asp-action="Index" asp-controller="DbManage" asp-area="Database">Database</a></li>
      <li> <a class="dropdown-item" asp-action="Index" asp-controller="Contact" asp-area="Contact">Quản lý liên hệ</a>
      </li>
      <li> <a class="dropdown-item" asp-action="Index" asp-controller="Role" asp-area="Identity">Quản lý Role</a></li>
      <li> <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Identity">Quản lý User</a></li>
      <li> <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Blog">Quản lý chuyên mục Blog
        </a></li>
      <li> <a class="dropdown-item" asp-action="Index" asp-controller="Post" asp-area="Blog">Quản lý bài viết blog
        </a></li>
      <li> <a class="dropdown-item" asp-action="Index" asp-controller="FileManager" asp-area="Files">Quản lý files
        </a></li>
      <li> <a class="dropdown-item" asp-action="Index" asp-controller="CategoryProduct" asp-area="Product">Quản lý danh mục sản phẩm
        </a></li>
        <li> <a class="dropdown-item" asp-action="Index" asp-controller="Product" asp-area="Product">Quản lý sản phẩm
        </a></li>

    </ul>
  </div> *@

}

Views/Shared/_PagingXTL.cshtml
@* 
    Model:
      - currentPage:int - Trang hiện tại
      - countPages:int - tổng số trang
      - generateUrl:delegate Func<int?, string> trả về URL tương ứng với trang p (1,2,3 ...)
*@

@model App.Models.PagingModel
@{
    int currentPage  = Model.currentpage;
    int countPages   = Model.countpages;
    var generateUrl  = Model.generateUrl;


    
    if (currentPage > countPages) 
      currentPage = countPages;

    if (countPages <= 1) return;
    

    int? preview = null;
    int? next = null;

    if (currentPage > 1)
        preview = currentPage - 1;

    if (currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();    

        
    int delta      = 5;             // Số trang mở rộng về mỗi bên trang hiện tại     
    int remain     = delta * 2;     // Số trang hai bên trang hiện tại

    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for (int i = 1; i <= delta; i++)
    {
        if (currentPage + i  <= countPages) {
            pagesRanges.Add(currentPage + i); 
            remain --;
        }
               
        if (currentPage - i >= 1) {
            pagesRanges.Insert(0, currentPage - i);
            remain --;
        }
            
    }    
    // Xử lý thêm vào các trang cho đủ remain 
    //(xảy ra ở đầu mút của khoảng trang không đủ trang chèn  vào)
    if (remain > 0) {
        if (pagesRanges[0] == 1) {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.Last() + 1 <= countPages) {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        }
        else {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.First() - 1 > 1) {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}

@* PHÁT SINH HTML*@

<ul class="pagination">
    <!-- Previous page link -->
    @if (preview != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview)">Trang trước</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
        </li>
    }
      
    <!-- Numbered page links -->
    @foreach (var pageitem in pagesRanges)
    {
        if (pageitem != currentPage) {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem)">
                    @pageitem
                </a>
            </li>
        }   
        else 
        {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only">(current)</span></a>
            </li>
        }
    }


    <!-- Next page link -->
    @if (next != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next)">Trang sau</a>
        </li>
    }
    else 
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
        </li>
    }
</ul>