Areas/Blog/Controllers/ViewPostController.cs
//using System.Data.Entity;
using App.Models;
using AppMvc.Net.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace AppMvc.Net.Areas.Blog.Controllers
{
    [Area("Blog")]
    public class ViewPostController : Controller
    {
        private readonly ILogger<ViewPostController> _logger;
        private AppDbContext _context;
        public ViewPostController(ILogger<ViewPostController> logger, AppDbContext context)
        {
            _logger = logger ;
            _context = context;
            
        }
        // GET: ViewPostController
        [Route("/post/{categoryslug?}")]
        public ActionResult Index(string categoryslug,[FromQuery(Name = "p")]int currentPage, int pageSize)
        {
            var categories = GetCategories();
            ViewBag.categories = categories;
            ViewBag.categoryslug = categoryslug;
            Category category = null;
            if(!string.IsNullOrEmpty(categoryslug))
            {
                category = _context.Category.Where(c => c.Slug == categoryslug)
                                            .Include(c => c.CategoryChildren)
                                            .FirstOrDefault();
                if(category == null)
                {
                    return NotFound("Khong thay category");
                }
            }
            var posts = _context.Posts
                                .Include(p=>p.Author)
                                .Include(p => p.PostCategories)
                                .ThenInclude(pc => pc.Category)
                                .AsQueryable();
            posts.OrderByDescending(p => p.DateUpdated);
            //Dung cach duoi cung dc nhung neu ko co AsQueryable thi dong code 53  posts = posts.Where(p =>p.PostCategories.Where(pc => ids.Contains(pc.CategoryId)).Any()); bi loi check lai sau
            //var posts = _context.Posts
                                //.Include(p=>p.Author).Include(p => p.PostCategories).ThenInclude(pc => pc.Category).OrderByDescending(p => p.DateUpdated);
            //var posts = (from c in _context.Posts select c).Include(p=>p.Author).Include(p => p.PostCategories).OrderByDescending(p => p.DateUpdated); //.ThenInclude(pc => pc.Category);
           if(category != null)
           {
            var ids = new List<int>();
            category.ChildCategoryIds(ids, null);
            ids.Add(category.Id);
            posts = posts.Where(p =>p.PostCategories.Where(pc => ids.Contains(pc.CategoryId)).Any());
           }
           int totalPosts =  posts.Count();
            if (pageSize <= 0 ) pageSize = 10;
            int countPages = (int) Math.Ceiling((double)totalPosts/pageSize);
            if(currentPage > countPages) currentPage = countPages;
            if(currentPage < 1) currentPage = 1;
            var pagingModel = new PagingModel
            {
                countpages = countPages,
                currentpage = currentPage,
                generateUrl = (pageNumber) => Url.Action("Index", new {
                    p = pageNumber,
                    pageSize = pageSize
                })

            };
            ViewBag.postIndex = (currentPage - 1) * pageSize;
            ViewBag.PagingModel = pagingModel;
            ViewBag.totalPosts = totalPosts;
            var postInPage =  posts.Skip((currentPage -1) * pageSize)
                                    .Take(pageSize);
                                  
            ViewBag.category = category;
            //var postmodel = posts.ToList();
            //return View(postmodel);
            return View(postInPage.ToList());

        }

        [Route("/post/{postslug}.html")]
        public ActionResult Detail(string postslug)
        {
            var categories = GetCategories();
            ViewBag.categories = categories;
            var post = _context.Posts.Where(p => p.Slug == postslug)
                                     .Include(p => p.Author)
                                     .Include(p => p.PostCategories)
                                     .ThenInclude(pc => pc.Category)
                                     .FirstOrDefault();
            if(post == null)
                return NotFound("Khong tim thay bai viet");
             Category category = post.PostCategories.FirstOrDefault()?.Category;
             ViewBag.category = category;
             var otherPosts = _context.Posts.Where(p => p.PostCategories.Any(c => c.Category.Id == category.Id) && p.PostId != post.PostId)
                                            .OrderByDescending(p => p.DateUpdated)
                                            .Take(5);
            ViewBag.otherPosts = otherPosts;
            return View(post);
        }

        private List<Category> GetCategories()
        {
            var categories = _context.Category
                                     .Include(c => c.CategoryChildren)
                                     .AsEnumerable() //nếu bỏ AsEnumerable thì data ko có category con ?? chưa hiểu tìm đọc lại sau. 
                                     .Where(c => c.ParentCategory == null)
                                     .ToList();
            return categories;
        }

    }
}

Areas/Product/Controllers/ViewProductController.cs
//using System.Data.Entity;
using App.Models;
using AppMvc.Net.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace AppMvc.Net.Areas.Product.Controllers
{
    [Area("Product")]
    public class ViewProductController : Controller
    {
        private readonly ILogger<ViewProductController> _logger;
        private AppDbContext _context;
        private readonly CartService _cartService;
        public ViewProductController(ILogger<ViewProductController> logger, AppDbContext context, CartService cartService)
        {
            _logger = logger;
            _context = context;
            _cartService = cartService;

        }
        // GET: ViewPostController
        [Route("/product/{categoryslug?}")]
        public ActionResult Index(string categoryslug, [FromQuery(Name = "p")] int currentPage, int pageSize)
        {
            var categories = GetCategories();
            ViewBag.categories = categories;
            ViewBag.categoryslug = categoryslug;
            CategoryProduct category = null;
            if (!string.IsNullOrEmpty(categoryslug))
            {
                category = _context.CategoryProducts.Where(c => c.Slug == categoryslug)
                                            .Include(c => c.CategoryChildren)
                                            .FirstOrDefault();
                if (category == null)
                {
                    return NotFound("Khong thay category");
                }
            }
            var products = _context.Products
                                .Include(p => p.Author)
                                .Include(p => p.Photos)
                                .Include(p => p.ProductCategoryProducts)
                                .ThenInclude(pc => pc.Category)
                                .AsQueryable();
            products.OrderByDescending(p => p.DateUpdated);
            //Dung cach duoi cung dc nhung neu ko co AsQueryable thi dong code 53  posts = posts.Where(p =>p.PostCategories.Where(pc => ids.Contains(pc.CategoryId)).Any()); bi loi check lai sau
            //var posts = _context.Posts
            //.Include(p=>p.Author).Include(p => p.PostCategories).ThenInclude(pc => pc.Category).OrderByDescending(p => p.DateUpdated);
            //var posts = (from c in _context.Posts select c).Include(p=>p.Author).Include(p => p.PostCategories).OrderByDescending(p => p.DateUpdated); //.ThenInclude(pc => pc.Category);
            if (category != null)
            {
                var ids = new List<int>();
                category.ChildCategoryIds(ids, null);
                ids.Add(category.Id);
                products = products.Where(p => p.ProductCategoryProducts.Where(pc => ids.Contains(pc.CategoryId)).Any());
            }
            int totalProducts = products.Count();
            if (pageSize <= 0) pageSize = 10;
            int countPages = (int)Math.Ceiling((double)totalProducts / pageSize);
            if (currentPage > countPages) currentPage = countPages;
            if (currentPage < 1) currentPage = 1;
            var pagingModel = new PagingModel
            {
                countpages = countPages,
                currentpage = currentPage,
                generateUrl = (pageNumber) => Url.Action("Index", new
                {
                    p = pageNumber,
                    pageSize = pageSize
                })

            };
            ViewBag.postIndex = (currentPage - 1) * pageSize;
            ViewBag.PagingModel = pagingModel;
            ViewBag.totalProducts = totalProducts;
            var productInPage = products.Skip((currentPage - 1) * pageSize)
                                    .Take(pageSize);

            ViewBag.category = category;
            //var postmodel = posts.ToList();
            //return View(postmodel);
            return View(productInPage.ToList());

        }

        [Route("/product/{productslug}.html")]
        public ActionResult Detail(string productslug)
        {
            var categories = GetCategories();
            ViewBag.categories = categories;
            var product = _context.Products.Where(p => p.Slug == productslug)
                                     .Include(p => p.Author)
                                     .Include(p => p.Photos)
                                     .Include(p => p.ProductCategoryProducts)
                                     .ThenInclude(pc => pc.Category)
                                     .FirstOrDefault();
            if (product == null)
                return NotFound("Khong tim thay bai viet");
            CategoryProduct category = product.ProductCategoryProducts.FirstOrDefault()?.Category;
            ViewBag.category = category;
            var otherProducts = _context.Products.Where(p => p.ProductCategoryProducts.Any(c => c.Category.Id == category.Id) && p.ProductId != product.ProductId)
                                           .OrderByDescending(p => p.DateUpdated)
                                           .Take(5);
            ViewBag.otherProducts = otherProducts;
            return View(product);
        }

        private List<CategoryProduct> GetCategories()
        {
            var categories = _context.CategoryProducts
                                     .Include(c => c.CategoryChildren)
                                     .AsEnumerable() //nếu bỏ AsEnumerable thì data ko có category con ?? chưa hiểu tìm đọc lại sau. 
                                     .Where(c => c.ParentCategory == null)
                                     .ToList();
            return categories;
        }
        /// Thêm sản phẩm vào cart
        [Route("addcart/{productid:int}", Name = "addcart")]
        public IActionResult AddToCart([FromRoute] int productid)
        {

            var product = _context.Products
                .Where(p => p.ProductId == productid)
                .FirstOrDefault();
            if (product == null)
                return NotFound("Không có sản phẩm");

            // Xử lý đưa vào Cart ...
            var cart = _cartService.GetCartItems();
            var cartitem = cart.Find(p => p.product.ProductId == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.quantity++;
            }
            else
            {
                //  Thêm mới
                cart.Add(new CartItem() { quantity = 1, product = product });
            }

            // Lưu cart vào Session
            _cartService.SaveCartSession(cart);
            // Chuyển đến trang hiện thị Cart
            return RedirectToAction(nameof(Cart));
        }
        // Hiện thị giỏ hàng
        [Route("/cart", Name = "cart")]
        public IActionResult Cart()
        {
            return View(_cartService.GetCartItems());
        }
        /// xóa item trong cart
        [Route("/removecart/{productid:int}", Name = "removecart")]
        public IActionResult RemoveCart([FromRoute] int productid)
        {
            var cart = _cartService.GetCartItems();
            var cartitem = cart.Find(p => p.product.ProductId == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cart.Remove(cartitem);
            }

            _cartService.SaveCartSession(cart);
            return RedirectToAction(nameof(Cart));
        }
        /// Cập nhật
        [Route("/updatecart", Name = "updatecart")]
        [HttpPost]
        public IActionResult UpdateCart([FromForm] int productid, [FromForm] int quantity)
        {
            // Cập nhật Cart thay đổi số lượng quantity ...
            var cart = _cartService.GetCartItems();
            var cartitem = cart.Find(p => p.product.ProductId == productid);
            if (cartitem != null)
            {
                // Đã tồn tại, tăng thêm 1
                cartitem.quantity = quantity;
            }
            _cartService.SaveCartSession(cart);
            // Trả về mã thành công (không có nội dung gì - chỉ để Ajax gọi)
            return Ok();
        }

        [Route("/checkout")]
        public IActionResult Checkout()
        {
           var cart = _cartService.GetCartItems();
           /*Xây dựng trang yêu cầu người dùng nhập thông tin sđt, địa chỉ gửi hàng ..
            Sau đó lấy thông tin cart gửi email cho khách hàng (xem phần contact)
            Lưu trữ thông tin vào cơ sở dữ liệu*/
            _cartService.ClearCart();
            return Content("Đã gửi đơn hàng");


        }

    }
}

Areas/Product/Views/ViewProduct/Cart.cshtml
@model List<AppMvc.Net.Models.CartItem>
    @{
        Layout = "_Layout";
    }

<h2>GIỎ HÀNG</h2>

@if (Model.Count > 0) {
  decimal total = 0;
  int stt = 1;
  
  <table class="table">
    <tr>
      <th>#</th>
      <th>Sản phẩm</th>
      <th>Giá</th>
      <th>Số lượng</th>
      <th>Thành tiền</th>
      <th></th>
    </tr>
    @foreach (var cartitem in Model)
    {
        var thanhtien = cartitem.quantity * cartitem.product.Price;
        total += thanhtien;

        <tr>
           <td>@(stt++)</td>
           <td>@cartitem.product.Title</td>
           <td>@(cartitem.product.Price.ToString("n0"))</td>
           <td><input asp-for="@cartitem.quantity" id="@($"quantity-{cartitem.product.ProductId}")"/></td>
           <td>@(thanhtien.ToString("n0"))</td>
           <td>
              <button class="btn btn-success updatecartitem" 
                    data-productid="@cartitem.product.ProductId">Cập nhật</button>
              <a asp-route="removecart" asp-route-productid="@cartitem.product.ProductId"
                class="btn btn-danger">Xóa</a>
           </td>
        </tr>
    }
      <tr>
          <td colspan="4" class="text-right">Tổng tiền</td>
          <td>@(total.ToString("n0"))</td>
          <td></td>
      </tr>
  </table>

  <a asp-controller="ViewProduct" asp-action="Checkout" class="btn btn-success">Gửi đơn hàng</a>

      @section Scripts {
        <script>
          $(document).ready(function () {
              $(".updatecartitem").click(function (event) {
                  event.preventDefault();
                  var productid = $(this).attr("data-productid");
                  var quantity = $("#quantity-" + productid).val();
                  $.ajax({
                      type: "POST",
                      url:"@Url.RouteUrl("updatecart")",
                      data: {
                          productid: productid,
                          quantity:quantity
                      },
                      success: function (result) {
                          window.location.href = "@Url.RouteUrl("cart")";
                      }
                  });
              });
          });
        </script>
      }

}
else {
  <p class="alert alert-danger">Giỏ hàng trống</p>
}

Areas/Product/Views/ViewProduct/Detail.cshtml
@using AppMvc.Net.Components
@{
     List<CategoryProduct> categories = ViewBag.categories as List<CategoryProduct>;
        ViewData["Title"] = Model.Title;
        CategoryProduct category = ViewBag.category as CategoryProduct;
        IQueryable<Product> otherProducts = ViewBag.otherProducts as IQueryable<Product>;
}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~">Home</a></li>
    @if(category != null)
    {
      var li = category.ListParents();
      foreach(var l in li)
      {
        <li class="breadcrumb-item">
          <a asp-action="Index" asp-route-categoryslug ="@l.Slug">@l.Title</a>
        </li>
         <li class="breadcrumb-item">
          <a asp-action="Index" asp-route-categoryslug ="@category.Slug">@category.Title</a>
        </li>
      }

    }
  </ol>
</nav>
<div class="detailpost">
    <h1>@ViewData["Title"]</h1>
    <div class="sapo">
        @Model.Description
    </div>
    <div>
      <p>
        Gia: <strong>@Model.Price</strong>
        <a asp-action="AddToCart" asp-route-productid = "@Model.ProductId" class="btn btn-danger">Dat hang</a>
      </p>
    </div>
    <div>
        <i>Cap nhat: @Model.DateUpdated</i>/
        Tac gia: <strong>@Model.Author.UserName</strong>
    </div>
    @if(Model.Photos != null)
    {
      <div class="d-flex flex-wrap">
        @foreach(var photo in Model.Photos )
        {
                  <img class="w-50" src= "/contents/Products/@photo.FileName" alt="">

        }

      </div>

    }
    <hr>
    @Html.Raw(Model.Content)

</div>
@section Sidebar {
   @await Component.InvokeAsync("AppMvc.Net.Components.CategoryProductSidebar", 
    new CategoryProductSidebar.CategorySidebarData()
    {
        Categories = categories,
        Level = 0,
        CategorySlug = category.Slug

    })
    <ul class="list-group">
        @foreach(var product in otherProducts)
        {
            <li class="list-group-item">
                <a asp-controller="ViewProduct" asp-action="Detail" asp-route-productslug ="@product.Slug">
                    @product.Title
                </a>
            </li>
        }
    </ul>
}

Areas/Product/Views/ViewProduct/Index.cshtml
@model List<Product>;
@using AppMvc.Net.Components;
@{
  List<CategoryProduct> categories = ViewBag.categories as List<CategoryProduct>;
  CategoryProduct category = ViewBag.category as CategoryProduct;
  ViewData["Title"] = (category != null) ? category.Title : "Tat ca san pham";
}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="~">Home</a></li>
    @if (category != null)
    {
      var li = category.ListParents();
      foreach (var l in li)
      {
        <li class="breadcrumb-item">
          <a asp-action="Index" asp-route-categoryslug="@l.Slug">@l.Title</a>
        </li>
      }

    }
  </ol>
</nav>
<h1>@ViewData["Title"]</h1>
@if (category != null)
{
  @* <p>@Html.Raw(category.Description)</p> *@
  <p>@category.Description</p>

}
else
{
  <p>Toan bo san pham trong tat ca cac danh muc...</p>
}
<hr>
<div class="d-flex flex-wrap justify-content-between">
  @foreach (var product in Model)
{
  var srcImg = "/contents/noimage.jpg";
  if(product.Photos.Any())
  {
    srcImg = $"/contents/Products/{product.Photos.FirstOrDefault().FileName}";
  }
    <div class="card mb-2" style="width: 32%;">
      <img src="@srcImg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">@product.Title</h5>
        <p class="card-text">@product.Description.</p>
        <p><strong class="text-danger">@product.ProductCategoryProducts.FirstOrDefault()?.Category.Title</strong></p>
        <p>Gia: <strong>@product.Price</strong></p>
        <div class="card-body">
          <a class="card-link" asp-action="Detail" asp-controller="ViewProduct" asp-route-productslug="@product.Slug">Chi
            tiet</a>
          <a asp-action="AddToCart" asp-route-productid="@product.ProductId" class="btn btn-primary ml-4">Dat hang</a>
        </div>
      </div>
    </div>


  @* <div class="d-flex align-items-cente border-bottom mb-3 pb-3">
<div class="flex-shrink-0">
<img src="/contents/noimage.jpg" alt="..." class="w-25">
</div>
<div class="flex-grow-1 ms-3">
<h5 class="mt-0">
<a asp-action="Detail" asp-controller="ViewPost" asp-route-postslug="@product.Slug">@product.Title</a>
</h5>
@product.Description
<div>
Chủ đề:
<strong class="text-danger">@product.ProductCategoryProducts.FirstOrDefault()?.Category.Title</strong>
</div>
<div class="author-row">
Tác giả: <strong>@product.Author</strong>|
Ngày cập nhật: <i>@product.DateUpdated.ToShortDateString()</i>

</div>
</div>
</div> *@

}

</div>


Đây là nội dung chuyên mục
@section Sidebar {
  @await Component.InvokeAsync("AppMvc.Net.Components.CategoryProductSidebar",
    new CategoryProductSidebar.CategorySidebarData()
{
  Categories = categories,
  Level = 0,
  CategorySlug = ViewBag.categoryslug

})
}
<partial name="_PagingXTL" model="@ViewBag.PagingModel"></partial>

Areas/Product/Views/ViewProduct/_LayoutProduct.cshtml
@{
    Layout = "_Layout";
}
<div class="row">
      <div class="col-md-3">
        @* THiết lập section Sidebar tham số false là ko thiết lập sidebar này cũng đc *@
        @RenderSection("Sidebar",false) </div>
    <div class="col-md-9">
        @RenderBody()
    </div>
  
</div>